#!/usr/bin/env bash

#Warning: All files must be decompressed

#Paths:
Output= /storages/parnamirim/iarasouza/tcruzi/genome/tcruzi/index-star \
Fasta= /storages/parnamirim/iarasouza/tcruzi/genome/tcruzi/genome-tcruzi/Trypanosoma_cruzi_gca_003719155.ASM371915v1.dna.toplevel.fa \
GTF= /storages/parnamirim/iarasouza/tcruzi/genome/tcruzi/gtf/Trypanosoma_cruzi_gca_003719155.ASM371915v1.56.gtf

#Index Biuld:
STAR --runThreadN 8 --runMode genomeGenerate --genomeDir $Output \
--genomeFastaFiles $Fasta --sjdbGTFfile $GTF
