#!/usr/bin/env bash

Warning: All files must be decompressed
"""
#Paths:
Output=/your/path/to/index_directory \
Fastqc=/your/path/to/fastqc_files.fa \
GTF=/your/path/to/gtf_files.gtf \

#Index Biuld:
STAR --runThreadN 8 --runMode genomeGenerate --genomeDir $Output \
--genomeFastaFiles $Fastqc --sjdbGTFfile $GTF
"""
